import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/redux/provider";
import Navbar from "@/component/navbar/Navbar";
import Footer from "@/component/footer/Footer";
import { Merienda } from 'next/font/google';

const merienda = Merienda({
  subsets: ['latin'],
  weight: ['400', '700'], // tuỳ bạn cần mấy trọng số
  variable: '--font-merienda', // dùng để áp dụng với Tailwind

});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Thời trang hiện đại",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merienda.variable} antialiased `}
      >
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
